- hosts: all
  vars:
        osx_pkgs:
                - emacs
                # no need to do this since 
                - cask

                # for python development
                - python3
                - flake8

        apt_pkgs:
                - emacs25
                - python3
                - flake8

  tasks:
        - name: OSX Homebrew package installs
          when: ansible_pkg_mgr == "homebrew"
          homebrew: name={{ item }}
          with_items: "{{ osx_pkgs }}"

        - name: apt package installs
          when: ansible_pkg_mgr == "apt"
          apt: name={{ item }}
          with_items: "{{ apt_pkgs }}"
          become: yes

        - name: copy .emacs
          copy: backup=yes
                src=../emacs/dot_emacs
                dest={{ ansible_env.HOME }}/.emacs

        - name: create .emacs.d and .emacs.d/tmp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/tmp

        - name: create .emacs.d/lisp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/lisp

        - name: copy .jshintrc
          copy: backup=yes
                src=../emacs/dot_jshintrc
                dest={{ ansible_env.HOME }}/.jshintrc

        - name: install cask
          shell: creates={{ ansible_env.HOME }}/.cask
                 warn=False
                 curl -fskSL https://raw.githubusercontent.com/cask/cask/master/go | python

        - name: copy cask file
          copy: src=../emacs/Cask
                dest={{ ansible_env.HOME }}/.emacs.d

        - name: run cask
          shell: cd {{ ansible_env.HOME }}/.emacs.d && {{ ansible_env.HOME }}/.cask/bin/cask install
