- hosts: all
  vars:
        osx_pkgs:
                - emacs

                # for python
                - python36
                - npm2
                - py36-flake8
                - py36-pep8
                - py36-pylint


  tasks:
        - name: Macport package installs
          become: true
          when: ansible_pkg_mgr == "macports"
          macports: name={{ item }} state=present
          with_items: "{{ osx_pkgs }}"

        # INSTALL RECENT EMACS
        - name: install the 'Development tools' package group
          become: true
          yum: name="@Development tools" state=present
          when: ansible_pkg_mgr == "yum"

        - name: select python36
          become: true
          when: ansible_pkg_mgr == "macports"
          shell: port select --set python python36

        # jshint for linting javascript, flycheck will use it out of the box
        - name: npm requirements
          become: true
          npm: name=jshint global=yes

        - name: copy .emacs
          copy: backup=yes
                src=../emacs/dot_emacs
                dest={{ ansible_env.HOME }}/.emacs

        - name: create .emacs.d and .emacs.d/tmp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/tmp

        - name: create .emacs.d/lisp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/lisp

        - name: copy .jshintrc
          copy: backup=yes
                src=../emacs/dot_jshintrc
                dest={{ ansible_env.HOME }}/.jshintrc

        - name: install cask
          shell: creates={{ ansible_env.HOME }}/.cask
                 warn=False
                 curl -fskSL https://raw.githubusercontent.com/cask/cask/master/go | python

        - name: copy cask file
          copy: src=../emacs/Cask
                dest={{ ansible_env.HOME }}/.emacs.d

        - name: run cask
          shell: cd {{ ansible_env.HOME }}/.emacs.d && {{ ansible_env.HOME }}/.cask/bin/cask install
