- hosts: all
  vars:
        osx_pkgs:
                - emacs

                # for python
                - python34
                - py34-pip

        pip_pkgs:
                # for python
                - flake8
                - pep8
                - pylint


  tasks:
        - name: Macport package installs
          become: true
          when: ansible_pkg_mgr == "macports"
          macports: name={{ item }} state=present
          with_items: osx_pkgs

        # INSTALL RECENT EMACS
        - name: install the 'Development tools' package group
          become: true
          yum: name="@Development tools" state=present
          when: ansible_pkg_mgr == "yum"

     # THE REST OF THE STEPS NEEDED
     # sudo yum groupinstall "Development Tools"
     # sudo yum install ncurses-devel
     # wget https://ftp.gnu.org/pub/gnu/emacs/emacs-24.5.tar.xz
     # tar -xvf emacs-24.5.tar.xz
     # cd emacs-24.5
     # ./configure --prefix=/usr --localstatedir=/var
     # make
     # sudo make install
     # sudo chown -v -R root:root /usr/share/emacs/24.5

        # - name: Yum package installs
        #   become: true
        #   yum: name={{ item }} state=latest
        #   with_items: os_pkgs

        - name: select pip34
          become: true
          when: ansible_pkg_mgr == "macports"
          shell: port select --set pip pip34

        - name: pip requirements
          become: true
          pip: name={{ item }}
          with_items: pip_pkgs

        - name: copy .emacs
          copy: backup=yes
                src=../emacs/dot_emacs
                dest={{ ansible_env.HOME }}/.emacs

        - name: create .emacs.d and .emacs.d/tmp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/tmp

        - name: create .emacs.d/lisp
          file: state=directory
                path={{ ansible_env.HOME }}/.emacs.d/lisp

        - name: install cask
          shell: creates={{ ansible_env.HOME }}/.cask
                 warn=False
                 curl -fskSL https://raw.githubusercontent.com/cask/cask/master/go | python

        - name: copy cask file
          copy: src=../emacs/Cask
                dest={{ ansible_env.HOME }}/.emacs.d

        - name: run cask
          shell: cd {{ ansible_env.HOME }}/.emacs.d && {{ ansible_env.HOME }}/.cask/bin/cask install

        - name: copy files
          copy: src=../emacs/{{ item }}
                dest={{ ansible_env.HOME }}/.emacs.d/lisp
          with_items:
                - pbcopy/pbcopy.el
