- hosts: all
  vars:
        osx_pkgs:
                direnv

        apt_pkgs:
                direnv

  tasks:
        - name: OSX Homebrew package installs
          when: ansible_pkg_mgr == "homebrew"
          homebrew: name={{ osx_pkgs }}

        - name: apt package installs
          when: ansible_pkg_mgr == "apt"
          apt: name={{ apt_pkgs }}
          become: yes

        - name: get git command line stuff
          get_url: url={{ item.url }}
                   dest={{ ansible_env.HOME }}/{{ item.dest }}
          with_items:
                - { dest: '.git-completion.bash',
                    url: 'https://raw.github.com/git/git/master/contrib/completion/git-completion.bash'}
                - { dest: '.git-prompt.sh',
                    url: 'https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh'}

        - name: copy dot files
          copy: src=../{{ item.src }}
                dest={{ ansible_env.HOME }}/{{ item.dest }}
          with_items:
                - { src: 'dot_bash_profile',  dest: '.custom_bash_profile' }
                - { src: 'dot_gitignore',  dest: '.gitignore' }
                - { src: 'dot_gitconfig',  dest: '.gitconfig' }
                - { src: 'dot_screenrc',   dest: '.screenrc' }
                - { src: 'dot_tmux.conf',  dest: '.tmux.conf' }
                - { src: 'dot_slate',      dest: '.slate' }
                - { src: 'dot_psqlrc',     dest: '.psqlrc' }
                - { src: 'dot_pylintrc',   dest: '.pylintrc' }
                - { src: 'dot_flake8rc',   dest: '.flake8rc' }
                - { src: 'dot_mypy_ini',   dest: 'mypy.ini' }
                - { src: 'dot_sqliterc',   dest: '.sqliterc' }

        - name: refer to .custom_bash_profile
          lineinfile: dest={{ ansible_env.HOME }}/.bash_profile
                      line='source ~/.custom_bash_profile'
                      create=yes