(source gnu)
(source melpa)

;;; Git
(depends-on "magit")
;;; OSX clipboard integration
(depends-on "pbcopy")
;;; ubuntu/linux needs xclip for clipboard integration
(depends-on "xclip")
;;; syntax checking
;; (depends-on "flycheck")
;;; rjsx for react
(depends-on "rjsx-mode")
;;; theme
(depends-on "zenburn-theme")
;;; python
(depends-on "elpy")
