(source gnu)
(source melpa)

;;; Git
(depends-on "magit")
;;; OSX clipboard integration
(depends-on "pbcopy")
;;; code auto completion
(depends-on "auto-complete")
;;; column width indicator
(depends-on "fill-column-indicator")
;;; web template editing mode
(depends-on "web-mode")
;;; syntax checking
(depends-on "flycheck")
;;; sphinx docstring creation
(depends-on "sphinx-doc")
;;; rjsx for react
(depends-on "rjsx-mode")
